02-02-2024 17:07:32:[INFO]:__main__:train:133 - Init Encoder model... - [0:00:00.050592]
02-02-2024 17:07:33:[INFO]:__main__:train:149 - Init Predictor model... - [0:00:01.426712]
02-02-2024 17:07:33:[INFO]:__main__:train:167 - Init MultiBlockMaskCollator module... - [0:00:01.571575]
02-02-2024 17:07:33:[INFO]:__main__:train:193 - Init local dataset loading module... - [0:00:01.572677]
02-02-2024 17:07:33:[ERROR]:utils:load_checkpoint:170 - Error loading the model! [Errno 2] No such file or directory: './artifacts/i-jepa-latest.pth.tar' - [0:00:01.619235]
02-02-2024 17:07:33:[INFO]:__main__:train:244 - Training has started for epoch 0 - [0:00:01.619766]
02-02-2024 17:14:24:[INFO]:__main__:train:296 - The loss at epoch 0 is 111.04776326566846 - [0:06:52.688269]
02-02-2024 17:14:25:[INFO]:utils:save_checkpoint:128 - Model checkpoint for epoch 0 is successful! - [0:06:53.790862]
02-02-2024 17:14:25:[INFO]:__main__:train:244 - Training has started for epoch 1 - [0:06:53.791231]
